config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :jobs
  root to: 'jobs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  mount_uploader :avatar, AvatarUploader

  JOB_TYPES = %w[
    full-time
    part-time
    contract
    internship
    freelance
    volunteer
  ].freeze

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @jobs = if params.key?(:job_type)
              Job.where(job_type: params[:job_type]).order('created_at DESC')
            else
              Job.all.order('created_at DESC')
            end
  end

  def show; end

  def new
    @job = current_user.jobs.build
  end

  def create
    @job = current_user.jobs.build(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_job
    @job = Job.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:title, :description, :company, :url, :job_type, :job_author, :remote, :apply_url,
                                :avatar, :location, :job_level)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def job_type(job_type)
    case job_type
    when 'full-time'
      content_tag(:span, 'full-time', class: 'border bg-emerald-500 text-white px-2 rounded')
    when 'part-time'
      content_tag(:span, 'part-time', class: 'border bg-orange-500 text-white px-2 rounded')
    when 'contract'
      content_tag(:span, 'contract', class: 'border bg-blue-500 text-white px-2 rounded')
    when 'internship'
      content_tag(:span, 'internship', class: 'border bg-green-500 text-white px-2 rounded')
    when 'freelance'
      content_tag(:span, 'freelance', class: 'border bg-red-500 text-white px-2 rounded')
    when 'volunteer'
      content_tag(:span, 'volunteer', class: 'border bg-purple-500 text-white px-2 rounded')
    end
  end

  def job_level(job_level)
    case job_level
    when 'entry'
      content_tag(:span, 'Entry', class: 'label label-primary')
    when 'mid'
      content_tag(:span, 'Mid', class: 'label label-success')
    when 'senior'
      content_tag(:span, 'Senior', class: 'label label-info')
    when 'manager'
      content_tag(:span, 'Manager', class: 'label label-warning')
    when 'executive'
      content_tag(:span, 'Executive', class: 'label label-danger')
    end
  end

  def job_author(job)
    user_signed_in? && current_user.id == job.user_id
  end
end

app/views/jobs/_form.html.erb
<%= simple_form_for @job, html: { multipart: true } do |f| %>
  <%= f.error_notification %>
  
  <div class="field">
    <div class="control">
      <%= f.input :title, input_html: { class: 'input' }, wrapper: false, label: { text: 'Title', class: 'label' }, placeholder: 'Dev' %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :apply_url, required: true, input_html: { class: "input" }, wrapper: false, label_html: { class: "label" }  %>
    </div>
  </div>

  <div class="columns">
    <div class="field">
      <div class="control">
        <label class="label">Job Type:</label>
        <div class="control">
          <span class="select">
              <%= f.input_field :job_type, collection: Job::JOB_TYPES, prompt: "Select a job type" %>
          </span>
        </div>
      </div>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :location, input_html: { class: "input" }, wrapper: false, label_html: { class: "label" }, hint: "City, State" %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <label for="job[remote]">
        <%= f.input_field :remote, as: :radio_buttons, collection: [["Remote", true], ["Onsite", false], ["Hybrid", false]], hint: "Remote or onsite?" %>
        Will this job be remote?
      </label>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <label class"experience">
        <%= f.input_field :job_level, as: :radio_buttons, collection: [["Entry", true], ["Mid", false], ["Senior", false], ["Manager", false], ["Executive", false]], hint: "What level of experience are you looking for?" %>
        What level of experience are you looking for?
      </label>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :description, required: true, input_html: { class: "textarea" }, wrapper: false, label_html: { class: "label" } %>
    </div>
  </div>

  <div class="columns">
    <div class="field">
      <div class="control">
        <label class="label">Company:</label>
        <div class="control">
          <span class="select">
            <%= f.input_field :company, required: true, input_html: { class: "input" }, wrapper: false, label_html: { class: "label" }, label: "Company" %>
          </span>
        </div>
      </div>
    </div>

    <div class="field column">
      <div class="control">
        <%= f.input :url, required: true, input_html: { class: "input" }, wrapper: false, label_html: { class: "label" }, label: "Company Website", placeholder: "http://company.com" %>
      </div>
    </div>

    <div class="columns">
      <div class="field column is-4">
        <div class="control">
          <label class="label">Logo Image</label>
          <div class="file">
            <label class="file-label">
              <%= f.input :avatar, as: :file, required: false, input_html: { class:"file-input job-avatar" }, label: false, wrapper: false %>
                <span class="file-cta">
                  <span class="file-icon"><i class="fa fa-upload"></i></span>
                  <span class="file-label">Choose a file…</span>
                </span>
            </label>
          </div>
        </div>
      </div>
      <div class="column">
        <output id="list"></output>
      </div>
  </div>


  <%= f.button :submit, class: "button" %>
<% end %>

app/views/jobs/_panel.html.erb
<nav class="space-y-2 sticky top-0">
  <div class="px-4 py-2 bg-white w-80">
    <p class="font-bold pb-3 text-gray-900">Filter by job type</p>
    <ul class="space-y-1 text-sm font-medium flex flex-wrap text-gray-500">
      <li class="pt-1">
        <button class="rounded-full mr-2 bg-blue-500 hover:bg-blue-700 py-2 px-4 text-white">
          <%= link_to "All", jobs_path %>
        </button>
      </li>
      <li>
        <button class="rounded-full mr-2 bg-blue-500 hover:bg-blue-700 py-2 px-4 text-white">
          <%= link_to "Full Time", jobs_path(job_type: "full-time") %>
        </button>
      </li>
      <li>
        <button class="rounded-full mr-2 bg-blue-500 hover:bg-blue-700 py-2 px-4 text-white">
          <%= link_to "Part Time", jobs_path(job_type: "part-time") %>
        </button>
      </li>
      <li>
        <button class="rounded-full mr-2 bg-blue-500 hover:bg-blue-700 py-2 px-4 text-white">
          <%= link_to "Contract", jobs_path(job_type: "contract") %>
        </button>
      </li>
      <li>
        <button class="rounded-full mr-2 bg-blue-500 hover:bg-blue-700 py-2 px-4 text-white">
          <%= link_to "Internship", jobs_path(job_type: "internship") %>
        </button>
      </li>
      <li>
        <button class="rounded-full mr-2 bg-blue-500 hover:bg-blue-700 py-2 px-4 text-white">
          <%= link_to "Freelance", jobs_path(job_type: "freelance") %>
        </button>
      </li>
      <li>
        <button class="rounded-full mx-2 bg-blue-500 hover:bg-blue-700 py-2 px-4 text-white">
          <%= link_to "Volunteer", jobs_path(job_type: "volunteer") %>
        </button>
      </li>
    </ul>
  </div>
</nav>

app/views/jobs/edit.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column">
        <h1 class="title">Editing Job</h1>
        <%= render 'form', job: @job %>
      </div>
    </div>
  </div>
</section>

app/views/jobs/index.html.erb
<div class="flex h-screen prose lg:prose-xl columns">
  <div class="column left w-full md:w-1/3 p-4 grid">
    <div class="w-72">
      <%= render 'panel' %>
    </div>
  </div>

  <div class="column right w-full lg:w-2/3 pl-12 pt-6">
    <% @jobs.each do |job| %>
    <div class="flex flex-col mb-5 border-b-2">
      <div class="column">
        <% if !job.avatar.file.nil? %>
          <%= link_to image_tag(job.avatar_url(:thumb), alt: job.job_author, width: 100, height: 100), job.url %>
        <% end %>
      </div>
      <div class="column">
        <h3 class="font-bold font-serif"><%= link_to job.title, job %></h3>
          <ul>
            <li><%= link_to job.company, job.url %></li>
            <li><%= link_to 'Apply now', job.apply_url %></li>
          </ul>
        <div class="flex flex-row justify-between">
          <p class="text-md prose"><%= sanitize(job.description.truncate(200, separator: '</p>'))%></p>
          <div class="text-xs">
            <%= job_type(job.job_type) %>
            <%= job_level(job.job_level) %>
          </div>
        </div>
        <% if current_user.try(:admin) || job_author(job) %>
          <ul class=>
            <li class="text-right text-xs">Admin Controls</li>
            <div class="flex flex-row text-xs justify-between w-28 mb-2 float-right">
              <li class="inline-block">
                <%= link_to 'View', job, class: 'text-blue-500 hover:underline underline-offset-6' %></li>
              <li class="">
                <%= link_to 'Edit', edit_job_path(job), class: 'text-blue-500 hover:underline underline-offset-6' %></li>
              <li class="">
                <%= link_to 'Delete', job, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button hover:underline underline-offset-6 text-red-500' %></li>
            </div>
          </ul>
        <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/jobs/new.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column">
        <h1 class="title">Post new Job</h1>
        <%= render 'form', job: @job %>
      </div>
    </div>
  </div>
</section

app/views/jobs/show.html.erb
<div class="columns">
  <div class="column">

    <p class="clock"> Posted <%= time_ago_in_words(@job.created_at) %> ago</p>
    <h1 class="title"><%= @job.title %></h1>

    <ul class="list">
      <li class="inline-block"><%= job_type(@job.job_type) %></li>
      <li class="inline-block"><i class=""></i> <%= @job.location %></li>
      <% if @job.remote? %>
        <li class="inline-block"> Remote Job</li>
      <% end %>
    </ul>

    <div class="content">
      <%= @job.description.html_safe %>
    </div>

    <%= link_to 'Apply to this job', @job.apply_url, class:"button" %>

  </div>

  <div class="column">

    <% if !@job.avatar.file.nil? %>
      <%= link_to image_tag(@job.avatar_url(:thumb), alt: @job.job_author, class: "has-text-centered"), @job.url %>
    <% end %>

    <div class="">
    <%= link_to @job.url do %>
      <i class=""></i>
    <% end %>
    </div>

    <% if current_user.try(:admin) || job_author(@job) %>
      <ul class="">
        <li class="">Admin controls: </li>
        <li class="inline-block">
          <%= link_to 'View', @job, class: 'button' %></li>
        <li class="inline-block">
          <%= link_to 'Edit', edit_job_path(@job), class: 'button' %></li>
        <li class="inline-block">
          <%= link_to 'Delete', @job, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button' %></li>
      </ul>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="scroll-smooth">
  <head>
    <title>Hura</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>

  <body class="container m-5 bg">
    <%= yield %>
  </body>
</html>